versions:
  # "6.0.1":
  #   folder: .
  # "6.0.2":
  #   folder: .
  # "6.0.3":
  #   folder: .
  "6.0.4":
    folder: .
  # "6.1.0":
  #   folder: .
  # "6.1.1":
  #   folder: .
  # "6.1.2":
  #   folder: .
  "6.1.3":
    folder: .
  "6.2.0":
    folder: .
  "6.2.1":
    folder: .
  "6.2.2":
    folder: .
  "6.2.3":
    folder: .
  "6.2.4":
    folder: .
